name: Node.js Package 2 Test

on:
  workflow_dispatch:
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clear npm cache
        run: npm cache clean --force

      # - name: Remove node_modules
      #   run: rm -rf node_modules

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Clear npm cache
        run: npm cache clean --force

      - uses: actions/checkout@v3
        with:
          path: .
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      # - name: List Files in Root Directory
      #   run: ls -a
      - name: Debug .npmrc
        run: |
          cat .npmrc
          echo $NODE_TOKEN
      - name: Debug npm Config
        run: npm config list
      - name: Log configuration
        run: npm config get registry
      - run: npm ci
      - run: npm publish
        env:
          NODE_TOKEN: ${{secrets.NODE_TOKEN}}
