name: Node.js Package

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clear npm cache
        run: npm cache clean --force

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    env:
      NODE_AUTH_TOKEN: ${{secrets.NODE_TOKEN}}
    steps:
      - name: Clear npm cache
        run: npm cache clean --force

      - uses: actions/checkout@v3
        with:
          path: .
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: '@next-levels'
      - run: |
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_TOKEN }}" >> .npmrc
      - name: Debug .npmrc
        run: |
          cat .npmrc
      - name: Debug NODE_AUTH_TOKEN
        run: echo $NODE_AUTH_TOKEN
      - name: Debug npm Config
        run: npm config list
      - name: Log configuration
        run: npm config get registry
      - run: npm ci
      - run: rm -rf ./out-tsc/*
      - run: tsc
      - run: npm publish
